---
title: "Homework 04: Tidy data and joins"
author: "Stephen Chignell"
date: "October 9, 2018"
output:
  github_document:
    toc: yes
---

# Overview

**Goal:** Solidify data wrangling skills by working on some realistic problems in the grey area between data aggregation and data reshaping.

**Assignment:** This is a “choose your own adventure”-style assignment, where you are expected to do the following two things:

- Pick one of the data reshaping prompts and do it.
- Pick one of the join prompts and do it.

It is fine to work with a new dataset and/or create variations on these problem themes.

#Data Reshaping
**Problem:** You have data in one “shape” but you wish it were in another. Usually this is because the alternative shape is superior for presenting a table, making a figure, or doing aggregation and statistical analysis.

**Solution:** Reshape your data. For simple reshaping, gather() and spread() from tidyr will suffice. Do the thing that is possible / easier now that your data has a new shape.


